### ISSUE TITLE
Inheriting Meta

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#102]
@pxjacomex , as we discussed this morning, you had problems inheriting the Meta class of models when these where inheriting. inheriting Meta is indeed possible, but [only if the parent class is declared as abstract](https://docs.djangoproject.com/en/4.2/topics/db/models/#meta-inheritance). I think we are indeed declaring the parent classes as abstract, see for example: https://github.com/ImperialCollegeLondon/paricia/blob/027a96fb56a766667ad8d37490686ce2fb34595b/measurement/models.py#L148

Could you provide any error message you are getting in relation to Meta not being available in the child classes?

**Comment by dalonsoa** [comment]
@pxjacomex , did you check this?

**Comment by pxjacomex** [comment]
I got what was happening; There were indexes declared in the grand parent
class (*BaseMeasurement*). So, I changed the index declaration in the
parent class (*create_meas_model*) and now the indexes are inherited to
children.
I've also tested it with postgres prompt:
[image: imagen.png]
Now, It's working as expected.
Thanks,
