### ISSUE TITLE
Gather benchmarking information

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#116]
The performance of the measurement models implemented in #114, #112 and #115  needs to be assessed as soon as possible to make appropriate adjustments, if not good enough. For that, we need specific information on how the system is typically used and the current performance.

In particular, we need:
- Number of measurement records (including all variables - temperature, precipitation, etc.) in the existing IMHEA system.
- Total time span of these records.
- Information on the typical queries for **raw data**:
  - Time span of data that is normally validated at once.
  - How long it takes to make these queries.
  - How often those queries are done.
- Information on the typical queries for **reports**:
  -  Most common type of reports requested (hourly, daily or monthly).
  - Time span of data that is normally validated at once.
  - How long it takes to make these queries.

Based on these, appropriate benchmarking tests will be setup with synthetic data.

**Comment by dalonsoa** [comment]
@ICHydro , I'm just checking on the status of this issue. Has there been any progress or do you need more information?

**Comment by ICHydro** [comment]
Sorry, this slipped a bit off my radar. Here is some further info. I will also add some example data to the repository.

- Number of measurement records (including all variables - temperature, precipitation, etc.) in the existing IMHEA system: _Currently there are 16.5 million records of orginal (raw) measurements in the database (but there is probably a similar amount of data waiting to be uploaded)_
- Total time span of these records: _earliest records are from 2001. We do not have any complete series that span 2001 - present but we will probably want to be able to process full time series of this length (which would be about 2 million records if we have a 20 year time series of 5 min measurements)_
- Information on the typical queries for raw data:
    - Time span of data that is normally validated at once: _validation (i.e. error checking of raw data as they come in: this is typically not a large amount as data are uploaded regularly, i.e. once a few months. So perhaps around 100k records at a time.
    - How long it takes to make these queries: I would need to benchmark the current system for this. 
    - How often those queries are done: _queries on raw data are not very common. The raw data are typically processed on uploading, both for error checking, and to generate derived data (e.g., aggregated time series at hourly and daily level). User queries are mostly on the processed data (e.g., hourly, daily, ...) and they can be for any time period, but I would expect that most queries are for a few years at most, and rarely for the entire time period_
- Information on the typical queries for reports:
    - Most common type of reports requested (hourly, daily or monthly): _Hard to say. Visualizations would ideally start at daily or monthly, but a user may zoom in down to the hourly level (though in that case only a subset of the data will be needed). The calculation of some of the summary indices requires the original hourly data, but this may not need to be done in real time._
    - Time span of data that is normally validated at once: _the calculation of some summary indices need the full time span, but again they may not need to be done in real time. Visualization is probably the most important real-time access, but the visualization widget may switch from daily to monthly data if the user zooms out, and vice versa._
    - How long it takes to make these queries: _I will try to do some tests on the current system but it is installed on a slow server so it tends to take long_

**Comment by dalonsoa** [comment]
@ICHydro , I've finished my benchmarking and summarised the findings in the wiki:

https://github.com/ImperialCollegeLondon/paricia/wiki/Performance-benchmarking

Do you have any news on querying time in the current system? I appreciate this might be challenging as whatever you can measure is likely to be convoluted with data manipulation and displaying, both done after the actual query is done, but just to have an idea of the timescale we are talking about.

**Comment by ICHydro** [comment]
Hi @dalonsoa, here are some benchmarks for querying the current system to download data as csv file:

- 92k timesteps: 2.3s
- 200k timesteps: 4.0s
- 321k timesteps: 6.0s
- 414k timesteps: 7.1s

Notes:
- This is each time for single sensor, which is the most type of typical query (i.e. scenario 1 in your summary)
- vm characteristics: 2GB Virtual Server – CentOS 7 (1 vCPU, 30 GB disk, Linux OS)
- I also tried querying for visualization which took much longer for each sensor, presumably because of the displaying, while I hope that is minimal in the case of creating a csv for download.

**Comment by dalonsoa** [comment]
OK, perfect. I'm going to repeat the quering calculations including saving data as CSV file to have a fairer comparison, also keeping the resources restricted.

**Comment by dalonsoa** [comment]
@ICHydro , I've included another run where saving the data to disk as CSV is included in the time. Please, have a look at the results, which look promissing:
https://github.com/ImperialCollegeLondon/paricia/wiki/Performance-benchmarking#low-resources-and-file-creation
