### ISSUE TITLE
Authentication for daily validation app

### ISSUE THREAD

**Issue by tsmbland** [ImperialCollegeLondon/paricia#153]
Currently the dash version of the daily validation app works without user authentication. We need to ensure that this is only accessible to logged-in users with appropriate permissions

**Comment by dalonsoa** [comment]
@ICHydro , could we have your thoughts about who should have access to what in the new Paricia during the meeting on Tuesday? 

The current permission system setup by Dan is described here: https://github.com/ImperialCollegeLondon/paricia#user-roles-and-permissions , but I'm not entirely sure if that is what you want. It seems to me that at least some data in the current system, like [station information](https://envisim.cv.ic.ac.uk/estacion/), is currently public. Is the report data also meant to be public?

**Comment by ICHydro** [comment]
Dan's setup seems largely OK, but we may want to give the users the possibility to choose whether they make their station information (and data) public or not. I will think about this a bit more, and we can discuss further on Tuesday.
