### ISSUE TITLE
Add map to the landing page

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#157]
Now that the reports and the validation are using dash/plotly from the onset, it might be pretty easy to integrate the use of maps to locate the stations easily, given that they include longitude and latitude information. 

Some examples about how this could be done are in here:
https://plotly.com/python/scatter-plots-on-maps/

## UPDATE

The map with the publicly available stations should be only in the landing page. The report and validation pages should be left as they are now.

**Comment by dalonsoa** [comment]
@ICHydro comment on this, please.

**Comment by ICHydro** [comment]
Looks good. It would be great to use OpenStreetMap as backdrop:

https://plotly.com/python/mapbox-layers/#openstreetmap-tiles-no-token-needed
