### ISSUE TITLE
Timezone issue when retrieving data?

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#161]
When making a query and plotting/downloading the data, do we want the data to be shown in the local timezone of the place where the data was acquired or the timezone of whoever is making the query?

**Comment by tsmbland** [comment]
See #162

**Comment by dalonsoa** [comment]
Let's check after #170 is implemented. It might not be an issue, anymore.

**Comment by dalonsoa** [comment]
@tsmbland is this still an issue after having completed #170? I believe that now we do everything in the timezone of the station, but just checking as you have interacted more with the front end.

**Comment by tsmbland** [comment]
This is all good now. I'll close the issue
