### ISSUE TITLE
Create a table describing the permission system

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#180]
Provide a more in depth description of how the permissions work, who has permission to do what and what should happen if someone deletes/updates some objects (eg. sensors).

**Comment by ICHydro** [comment]
That is done now - see wiki. I have made two tables, one with the current permissions, and one with desired permissions that we may add at a later stage. Please adjust to reflect the current state of development.

**Comment by dalonsoa** [comment]
@tsmbland have a look at https://github.com/ImperialCollegeLondon/paricia/wiki/Permissions-table
