### ISSUE TITLE
Make object ownership compulsory

### ISSUE THREAD

**Issue by tsmbland** [ImperialCollegeLondon/paricia#221]
Currently owner is an optional field for the models. This was required to get it to work with the initial data, however we need to make ownership compulsory so we'll have to make some changes here

**Comment by tsmbland** [comment]
Technically `owner` is still an optional field in the sense that `null=True` and `blank=True`. That said, for all intents and purposes, ownership is mandatory as any new objects created through the admin will be owned by whoever created them, and this cannot be changed.

The only reason I haven't changed the `null`/`blank` options in the model is that this wouldn't work with the initial data, which doesn't have an owner specified.

@dalonsoa Is there anything I need to do for this, or is it ok to close the issue?

**Comment by dalonsoa** [comment]
Let's leave it as it is, for now. It will need to be tackled when - in the future, someone - porting the existing production system to Paricia.

**Comment by dalonsoa** [comment]
A solution for this could be to add a "default admin" user that gets assigned anything imported to the DB "manually", i.e. not using the forms. Something to consider.
