### ISSUE TITLE
Adding/editting objects possible in the API but not in the Admin

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#231]
Possibly related to #229 and #214.

Objects cannot be added or modified in the Admin, even if you are the admin. However, you can use the API to modify objects at will - as long as you are logged in. For example, you can go https://liionsden.rcs.ic.ac.uk/station/station/7/ and edit the properties of station 7 . It does not matter if they are private: they are visible and editable (at least by the admin). 

Measurements cannot be added via de admin, either, since to add a measurement you need to select an Station and a Variable, and not being the owner of any of the existing ones, I cannot choose them in the form.

**Comment by tsmbland** [comment]
I'm pretty sure the admin site is working properly now, as of #234 

I haven't thought about the API at all. Is this something you wan't me to look into next, or are we removing this feature in favour of the admin site?
