### ISSUE TITLE
Date & Time consistency

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/paricia#25]
In principle, it would be good to set `USE_TZ = TRUE` in `settings.py` (which we have now done) to store overall consistent datetime objects in the databse. From [docs](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/):

> When support for time zones is enabled, Django stores datetime information in UTC in the database, uses time-zone-aware datetime objects internally, and translates them to the end user’s time zone in templates and forms.

We probably want time zones to factor into the date-time information of uploaded data, so everything can be stored consistently, then displayed properly according to the use case. E.g. The local time zone of recorded data should be displayed alongside any data/plots. 

Overall, the current database collects data from two timezones. To make this code fully useful and international, we should plan for any time zones to in principle be used. 

We should check this behaviour carefully when we have a working MVP. 

From Pablo: 

> I have a vague recollection that it was important for it to 'match' the server time setting (operating system) and the database time setting (POSTGRES).
I'm not sure what the reason was exactly, but it seems to me that a possible cause was that this was necessary for the import of data using the import functions.

> It seems to me that this was related to the data type provided by DJANGO models.DecimalField() which translates it to POSTGRES as TIMESTAMP WITH TIMEZONE. For DJANGO there is no WITHOUT TIMEZONE option

> Another possible reason why USE_TZ = XXX was important, I think, is because when viewing the time series using pyplot or the javascript plugins for plots, an offset in the time was shown in the data display.

> In any case, I believe that it is possible to change to the USE_TZ = TRUE option, but it will be necessary to check that the import of data by file load does not generate a shift (shift) of time (due to the time zone). That is, it must be compared that the time of the data that is saved in the database coincides with the time of the upload CSV file. It should also be checked that the display does not generate time shift.

> The interesting thing is that the problem that I had here (ZONE -5GMT) cannot possibly be replicated by you since you are in a 0GMT zone.
```

**Comment by dalonsoa** [comment]
Superseded by #104
