### ISSUE TITLE
Menu item population

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/paricia#27]
Hardcoding menu items in the home app and then dynamically creating the menu depending on user permissions and the availability of the other apps is not the most Django-ish approach. A thing to review in the future.

**Comment by dalonsoa** [comment]
We have concluded we should have in the menu:
- **Reports**: Always visible. Content depending on permission of the data and the user.
- **Validation**: Only visible for registered users that own a Station.
- **API**: Only visible for registered users.
- **Login**: Always visible.

Within the API, me menu should expand to give access to all the end points of Paricia.

**Comment by dalonsoa** [comment]
No longer relevant.
