### ISSUE TITLE
Delta t already exists.

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#328]
**Description**
When trying to add an entry for stations > Delta T, I get an error message:

Delta t with this Time interval (minutes) already exists.

As I don't have an entry for this time interval (5 min) yet, presumably another user already has a (private) entry with the same value, and the system does not allow more than one entry with the same value?

**To Reproduce**
1. Go to Home › Station › Delta ts › Add delta t
2. Add an entry with a time interval of 5 minutes

**Expected behavior**
Duplicate entries should be allowed because a user may have a private entry that is not accessible for another user.

**Screenshot**
![Screenshot 2024-09-20 002905](https://github.com/user-attachments/assets/4cd67c30-66a6-408e-8cf3-b11c97caff65)

**Additional context**
If this is unique to Delta T then it may not be necessary to solve it - see feature request on removing Delta T. If this is a problem that also occurs with other objects then it needs to be solved.

**Comment by dalonsoa** [comment]
Good point. Will action after discussing https://github.com/ImperialCollegeLondon/paricia/issues/329, since it might be `Delta T` is not needed at all.

**Comment by dalonsoa** [comment]
As DeltaT will be removed as part of #329, this is no longer relevant.
