### ISSUE TITLE
Private objects from another user are visible in the filter tool

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#330]
**Describe the bug**
Private objects from another user are visible in the filter tool. For example, in the screenshot I can see station names that I have not created and are not visible in my "stations" tab.

**To Reproduce**
1. Go to Home › Measurement › Measurements
2. Browse "FILTER" column
4. Observe stations that are not created by a user and not public

**Expected behavior**
Private entries from other users should not be visible here

**Screenshots**
![Screenshot 2024-09-20 004040](https://github.com/user-attachments/assets/bdbd044b-a6e5-4a7a-afc6-4ca037ffde21)

**Additional context**
At least I assume that the stations that are visible in the screenshot are private stations by another user because they do not show up in the "stations" tab, and I can also not select them when importing data.

**Comment by dalonsoa** [comment]
Seems like a limitation of `django-guardian`. Bu we will explore the options.

**Comment by dalonsoa** [comment]
As we are implemented separate views for everything and normal users will no longer need to access the Admin - indeed, they will be removed that permission - this is no longer an issue. The only people with access to the Django Admin will be Admin, who by definition can see everything.
