### ISSUE TITLE
Allow users to delete objects

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#337]
**Is your feature request related to a problem or limitation? Please describe.**
There is no clear way for users to delete objects they have created. We should probably discourage users from doing so because this may create issues with dependencies between tables, and instead encourage them to change an existing object (for example if they made a mistake in the objects properties). However, there may be cases where deleting an object is needed (for example if there are duplicate entries). 

**Describe the solution you'd like**
Allow users to delete objects, such as a station. 

**Additional context**
Should we allow users to delete a data import, and the associated data with it? There may not be a need to do so; even if the wrong data are uploaded, a user can always upload a new file and reprocess. But there may be use cases where a user really wants to delete all the data.

**Comment by dalonsoa** [comment]
Users can delete their own objects. Just enter into the object and click in the Delete button at the bottom-right. 

<img width="698" alt="image" src="https://github.com/user-attachments/assets/f08c1515-1c4a-48e7-b038-e0bad7a56436">

HOWEVER, if the object is being used somwhere else - by the same user or by other, if it was public - there will be a message saying that the object cannot be removed.

**Comment by ICHydro** [comment]
Thanks. Sorry for missing this. We may want to allow public objects to be removed as well, if they are not being used. I suppose that a user can already do this by making an object private and then removing it?

**Comment by dalonsoa** [comment]
Being public is not the limitation, it is being used as ForeignKey by other object. We could allow deleting an object being used somewhere else, but then we need to decide how to proceed, if leaving that orphan or what.

**Comment by dalonsoa** [comment]
Seems this is not really an issue, so closing, for now.
