### ISSUE TITLE
Link data import object with data via ForeignKey with a cascade relation when deleting the former

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#338]
**Is your feature request related to a problem or limitation? Please describe.**
It is not clear what happens when a user changes a data import by uploading a new file and reprocessing it. Are the original data from the previous file deleted?

**Comment by dalonsoa** [comment]
This ties with #334 . At the moment, there's a complete disconnection - as there were in the old system, as far as I know - between the data import object and the data actually imported. Deleting the data import will not change the actual data, and re-processing the data will just delete the existing data if they overlap (same time period, variable and station).

I'd suggest we link both - the data import and the actual data - via a Foreign Key such that if a user deletes or reprocess the data import, we know exactly what data entries need to be modified. What we can do nothing about is about the existing - if any - reports, as these aggregate data that can span multiple files.
