### ISSUE TITLE
Automatically refresh data import page to capture current import status

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#339]
**Is your feature request related to a problem or limitation? Please describe.**
When data are imported via a data import, "status" describes the status of the processing. The following improvements can be made:
- add a "reload" button to update the status (large datasets can take a while to be processed) or alternatively update the status automatically.
- It is not clear whether daily and monthly aggregates are calculated automatically or at a later stage. it is probably best not to do this automatically, but enable to user to request the calculation at a later stage (for example after validation).

**Comment by dalonsoa** [comment]
> * It is not clear whether daily and monthly aggregates are calculated automatically or at a later stage. it is probably best not to do this automatically, but enable to user to request the calculation at a later stage (for example after validation).

No aggregates are calculated during import, only after validation. 

I'll look into automatically refreshing the page.

**Comment by dalonsoa** [comment]
This might require a separate view, rather than using the Admin for data ingestion. It is fine, as other issues flagged are pointing to several limitations of the Django Admin, so I think it will be best to cut all of those issues and create separate views for the data import list and detail (and add/edit).

**Comment by dalonsoa** [comment]
Separate views have now been implemented for all models - including Data Import one - with a refresh button. As usual, CTR-R (or CMD-R in macOS) also reloads the page.
