### ISSUE TITLE
the "reports" and "validation" pages are very slow for large datasets

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#340]
**Is your feature request related to a problem or limitation? Please describe.**
The "reports" and "validation" pages become very slow when processing large datasets (triggering "the page is slowing down firefox" warnings in Firefox). Presumably this is because the site is loading all the data in the time series, which can be several thousands or even millions of data points. We should avoid loading all the data, and instead only the data that are strictly needed for the user interface. See also discussion on [issue 222](https://github.com/ImperialCollegeLondon/paricia/issues/222) in relation to the visualization of large time series.

**Describe the solution you'd like**
Minimize the data that are held in client-side memory, instead working with repeated requests to the database when the interface is updated.

**Comment by dalonsoa** [comment]
Let's schedule this. It was in the todo list already.
