### ISSUE TITLE
"Detail of selected day" is disabled when a day is selected

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#341]
**Describe the bug**
In the "validation" page, the "Detail of selected day" tab is disabled even though a day is selected.

**To Reproduce**
1. Go to the "validation" page
2. Load data for a station, select a day
3. See error

**Expected behavior**
The "Detail of the selected day" tab should be enabled

**Screenshots**

**Additional context**
![Screenshot 2024-09-20 170341](https://github.com/user-attachments/assets/f7051861-2dd6-4af0-bf3c-caa485ec0891)

**Comment by dalonsoa** [comment]
As [explained in the documentation](https://imperialcollegelondon.github.io/paricia/validation/#the-detail-for-the-day), the tab for the detail of the day opens when the chosen day is selected in the date selector at the bottom right. The checkbox is used to select/deselect what data will be active for calculating the reports, also as [explained in the docs](https://imperialcollegelondon.github.io/paricia/validation/#confirming-validation).

**Comment by ICHydro** [comment]
Thanks. Sorry for missing this. Closing this issue.
