### ISSUE TITLE
extend documentation further and split up in sections for using, installing, and developing paricia

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#355]
**Is your feature request related to a problem or limitation? Please describe.**
The documentation should be developed further. I suggest splitting it up more clearly in sections for users of the system, installation, and developers. 

**Describe the solution you'd like**
Perhaps we can have menu items in the top bar like "User guide", "Installation", and "Developer guide".

**Describe alternatives you've considered**
Using different sections in the left-hand column, but this can become quite long.

**Comment by dalonsoa** [comment]
Could you further develop the idea of what the documentation structure should look like based on the type of users and what they will like to see? Maybe a few bullet points with specific sections that we can use as skeleton to reorganise the documentation.
