### ISSUE TITLE
Generalising code

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/paricia#6]
**Problem:** In places, the code is very WET (write everything twice). 

**Proposed Solution:** Some things, specifically not models, can be easily generalised. They should be listed here and tackled at some point. Models may be tougher to generalise given that there is existing data which needs to be preserved. 

-  [ ] ExcelResponse e.g. used in `datalogger.functions`, `estacion.functions` to export summary tables. (Could also look at django_tables2 for this).

**Comment by dalonsoa** [comment]
Not relevant anymore.
