### ISSUE TITLE
API functionality

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/paricia#74]
Below is a list of features that should be present in the system (adapted from Anaconda2.0 capabilities). Those with TODO are to do with permissions/roles/authentication so will be tackled next.

In general there is a `ListCreateAPIView` and a `RetrieveUpdateDestroyAPIView` for each model. The exception is the Measurement app (where the actual time-series data is stored) which only have `ListAPIView` because generally these should be added and updated by the functions in the Importing app. We will need to revisit this in the future though.

The plan is to add the necessary permission requirements to each view, then only users in the specific groups will be able to carry out those specific actions.

### Core Functionalities
- List of available stations/sensors
- Sensors detail
- Time series data with range selection
- Import
  - Upload new sensor data
 
### Authentication (TODO)
 - Multil-user model
 - User login

### Management
- Users management (TODO)
  - User CRUD
- Privilege management (Manage users for a station) (TODO)
  - Add user as a sensor viewer
  - Add user as a sensor owner
- Sensors/station management CRUD
- Parameters management CRUD
  - Variables (temperate, water level, etc.)
  - Dimensions (meters, celsius, etc.)

**Comment by dalonsoa** [comment]
Not applicable for the time being.
