### ISSUE TITLE
Fetching relative depth data

### ISSUE THREAD

**Issue by HelNershingThapa** [ImperialCollegeLondon/paricia#92]
Would it be possible to send in relative data in responses? This concerns implementing API endpoints on the front end.

I'll try to explain this by implementing a table with the following headers.

| Sensor type | Sensor brand | Variable name | Station code | Minimum |  Maximum | 
| ----------- | ----------- | ----------- |----------- |----------- | ----------- |

To fill in the data in the above table, with the current implementation, we'd fetch the response from `/variable/sensorinstallation`, fetch individual variable, station and sensor information, and then map each corresponding detail value within installed sensors. For its implementation on the front-end, we'd then require to group related to their root data. As far as I know, this implementation is less complex on the backend than the front-end. Showing units for maximum and minimum would require additional API requests.

So this issue is a request to supply nested depth information rather than just the identifier, which would require additional API requests.

**Comment by dandavies99** [comment]
Hi both, yes that sounds sensible to me - definitely easier to modify the behaviour in the backend. It [looks like](https://www.django-rest-framework.org/api-guide/serializers/#specifying-nested-serialization) this should be as easy as adding `depth = 2` to the `Meta` class of whichever serializers we need. I've tested this locally and it seems to work (see image). 

It will probably be easier for you to make those changes yourselves in this repo. Feel free to create a new branch and submit a PR. 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/5871253/182833882-db63a125-fa56-48b6-9ac2-9cdcbe98da3a.png">

**Comment by HelNershingThapa** [comment]
With https://github.com/ImperialCollegeLondon/paricia/commit/c9e9e3992ae4bf76fc56a310d29510db09619f8b being merged in, I believe this issue can be closed
